/*
 * CRS account authorisation API
 * This service exposes an API to validate approver’s right of disposal to account. This API accesses the same authorization data as is used when TietoEvry validates approver data.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.evry.model;

import java.util.Objects;
import java.util.Arrays;
import com.evry.model.AccountAccessResult;
import com.evry.model.CustomerPublic;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * The autorisation response including additional data
 */
@Schema(description = "The autorisation response including additional data")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-20T05:28:54.388Z[GMT]")
public class AuthorisationResponse {
  @SerializedName("customerPublic1")
  private CustomerPublic customerPublic1 = null;

  @SerializedName("customerPublic2")
  private CustomerPublic customerPublic2 = null;

  @SerializedName("accountAccessResultList")
  private List<AccountAccessResult> accountAccessResultList = new ArrayList<>();

  public AuthorisationResponse customerPublic1(CustomerPublic customerPublic1) {
    this.customerPublic1 = customerPublic1;
    return this;
  }

   /**
   * Get customerPublic1
   * @return customerPublic1
  **/
  @Schema(required = true, description = "")
  public CustomerPublic getCustomerPublic1() {
    return customerPublic1;
  }

  public void setCustomerPublic1(CustomerPublic customerPublic1) {
    this.customerPublic1 = customerPublic1;
  }

  public AuthorisationResponse customerPublic2(CustomerPublic customerPublic2) {
    this.customerPublic2 = customerPublic2;
    return this;
  }

   /**
   * Get customerPublic2
   * @return customerPublic2
  **/
  @Schema(description = "")
  public CustomerPublic getCustomerPublic2() {
    return customerPublic2;
  }

  public void setCustomerPublic2(CustomerPublic customerPublic2) {
    this.customerPublic2 = customerPublic2;
  }

  public AuthorisationResponse accountAccessResultList(List<AccountAccessResult> accountAccessResultList) {
    this.accountAccessResultList = accountAccessResultList;
    return this;
  }

  public AuthorisationResponse addAccountAccessResultListItem(AccountAccessResult accountAccessResultListItem) {
    this.accountAccessResultList.add(accountAccessResultListItem);
    return this;
  }

   /**
   * Get accountAccessResultList
   * @return accountAccessResultList
  **/
  @Schema(required = true, description = "")
  public List<AccountAccessResult> getAccountAccessResultList() {
    return accountAccessResultList;
  }

  public void setAccountAccessResultList(List<AccountAccessResult> accountAccessResultList) {
    this.accountAccessResultList = accountAccessResultList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorisationResponse authorisationResponse = (AuthorisationResponse) o;
    return Objects.equals(this.customerPublic1, authorisationResponse.customerPublic1) &&
        Objects.equals(this.customerPublic2, authorisationResponse.customerPublic2) &&
        Objects.equals(this.accountAccessResultList, authorisationResponse.accountAccessResultList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerPublic1, customerPublic2, accountAccessResultList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorisationResponse {\n");
    
    sb.append("    customerPublic1: ").append(toIndentedString(customerPublic1)).append("\n");
    sb.append("    customerPublic2: ").append(toIndentedString(customerPublic2)).append("\n");
    sb.append("    accountAccessResultList: ").append(toIndentedString(accountAccessResultList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
