/*
 * CRS account authorisation API
 * This service exposes an API to validate approver’s right of disposal to account. This API accesses the same authorization data as is used when TietoEvry validates approver data.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.evry.model;

import java.util.Objects;
import java.util.Arrays;
import com.evry.model.AccountAccess;
import com.evry.model.CustomerPublic;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * The autorisation request
 */
@Schema(description = "The autorisation request")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-20T05:28:54.388Z[GMT]")
public class AuthorisationRequest {
  @SerializedName("customerPublic1")
  private CustomerPublic customerPublic1 = null;

  @SerializedName("customerPublic2")
  private CustomerPublic customerPublic2 = null;

  @SerializedName("accountList")
  private List<AccountAccess> accountList = new ArrayList<>();

  public AuthorisationRequest customerPublic1(CustomerPublic customerPublic1) {
    this.customerPublic1 = customerPublic1;
    return this;
  }

   /**
   * Get customerPublic1
   * @return customerPublic1
  **/
  @Schema(required = true, description = "")
  public CustomerPublic getCustomerPublic1() {
    return customerPublic1;
  }

  public void setCustomerPublic1(CustomerPublic customerPublic1) {
    this.customerPublic1 = customerPublic1;
  }

  public AuthorisationRequest customerPublic2(CustomerPublic customerPublic2) {
    this.customerPublic2 = customerPublic2;
    return this;
  }

   /**
   * Get customerPublic2
   * @return customerPublic2
  **/
  @Schema(description = "")
  public CustomerPublic getCustomerPublic2() {
    return customerPublic2;
  }

  public void setCustomerPublic2(CustomerPublic customerPublic2) {
    this.customerPublic2 = customerPublic2;
  }

  public AuthorisationRequest accountList(List<AccountAccess> accountList) {
    this.accountList = accountList;
    return this;
  }

  public AuthorisationRequest addAccountListItem(AccountAccess accountListItem) {
    this.accountList.add(accountListItem);
    return this;
  }

   /**
   * Get accountList
   * @return accountList
  **/
  @Schema(required = true, description = "")
  public List<AccountAccess> getAccountList() {
    return accountList;
  }

  public void setAccountList(List<AccountAccess> accountList) {
    this.accountList = accountList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorisationRequest authorisationRequest = (AuthorisationRequest) o;
    return Objects.equals(this.customerPublic1, authorisationRequest.customerPublic1) &&
        Objects.equals(this.customerPublic2, authorisationRequest.customerPublic2) &&
        Objects.equals(this.accountList, authorisationRequest.accountList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerPublic1, customerPublic2, accountList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorisationRequest {\n");
    
    sb.append("    customerPublic1: ").append(toIndentedString(customerPublic1)).append("\n");
    sb.append("    customerPublic2: ").append(toIndentedString(customerPublic2)).append("\n");
    sb.append("    accountList: ").append(toIndentedString(accountList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
