/*
 * CRS account authorisation API
 * This service exposes an API to validate approver’s right of disposal to account. This API accesses the same authorization data as is used when TietoEvry validates approver data.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.evry.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CustomerPublic
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-20T05:28:54.388Z[GMT]")
public class CustomerPublic {
  @SerializedName("publicID")
  private String publicID = null;

  @SerializedName("isoCountryCode")
  private String isoCountryCode = null;

  /**
   * The AML status of the customer. Only used in API response and any values in request will be ignored
   */
  @JsonAdapter(AmlStatusEnum.Adapter.class)
  public enum AmlStatusEnum {
    OK("OK"),
    NOT_VALIDATED("NOT_VALIDATED"),
    FAILED_NAME_CHECK("FAILED_NAME_CHECK");

    private String value;

    AmlStatusEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static AmlStatusEnum fromValue(String text) {
      for (AmlStatusEnum b : AmlStatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<AmlStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AmlStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AmlStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return AmlStatusEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("amlStatus")
  private AmlStatusEnum amlStatus = null;

  public CustomerPublic publicID(String publicID) {
    this.publicID = publicID;
    return this;
  }

   /**
   * The sosial security number of the user
   * @return publicID
  **/
  @Schema(required = true, description = "The sosial security number of the user")
  public String getPublicID() {
    return publicID;
  }

  public void setPublicID(String publicID) {
    this.publicID = publicID;
  }

  public CustomerPublic isoCountryCode(String isoCountryCode) {
    this.isoCountryCode = isoCountryCode;
    return this;
  }

   /**
   * Get isoCountryCode
   * @return isoCountryCode
  **/
  @Schema(description = "")
  public String getIsoCountryCode() {
    return isoCountryCode;
  }

  public void setIsoCountryCode(String isoCountryCode) {
    this.isoCountryCode = isoCountryCode;
  }

  public CustomerPublic amlStatus(AmlStatusEnum amlStatus) {
    this.amlStatus = amlStatus;
    return this;
  }

   /**
   * The AML status of the customer. Only used in API response and any values in request will be ignored
   * @return amlStatus
  **/
  @Schema(description = "The AML status of the customer. Only used in API response and any values in request will be ignored")
  public AmlStatusEnum getAmlStatus() {
    return amlStatus;
  }

  public void setAmlStatus(AmlStatusEnum amlStatus) {
    this.amlStatus = amlStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerPublic customerPublic = (CustomerPublic) o;
    return Objects.equals(this.publicID, customerPublic.publicID) &&
        Objects.equals(this.isoCountryCode, customerPublic.isoCountryCode) &&
        Objects.equals(this.amlStatus, customerPublic.amlStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(publicID, isoCountryCode, amlStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerPublic {\n");
    
    sb.append("    publicID: ").append(toIndentedString(publicID)).append("\n");
    sb.append("    isoCountryCode: ").append(toIndentedString(isoCountryCode)).append("\n");
    sb.append("    amlStatus: ").append(toIndentedString(amlStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
